os: linux
dist: focal

language: generic

env:
  global:
  - GIT_NAME: Spirillen
  - GIT_EMAIL: 44526987+spirillen@users.noreply.github.com
  - TRAVIS_REPO_SLUG: "${TRAVIS_REPO_SLUG}"
  - GIT_BRANCH: "${TRAVIS_BRANCH}"
  - TZ: UTC
  - PYTHON_VERSION: 3.9.1
  - SCRIPT_SOURCE_URI: https://raw.githubusercontent.com/dns-test/script-hub/master
  #- PYFUNCEBLE_DEBUG: TRUE
  #- PYFUNCEBLE_DEBUG_ON_SCREEN: false
  #- Pyfunceble_version: 'PyFunceble@dev'
  - Pyfunceble_version: 'PyFunceble@4.0.0-dev'
  - PYFUNCEBLE_CONFIG_DIR: "${TRAVIS_BUILD_DIR}/.pyfunceble/"
  - PYFUNCEBLE_OUTPUT_LOCATION: "${TRAVIS_BUILD_DIR}/.pyfunceble/"
  - PYFUNCEBLE_AUTO_CONFIGURATION: true
  - PYFUNCEBLE_DB_CHARSET="${DB_CHARSET}"
  - PYFUNCEBLE_DB_HOST="${DB_HOST}"
  - PYFUNCEBLE_DB_NAME="${DB_NAME}"
  - PYFUNCEBLE_DB_USERNAME="${DB_USERNAME}"
  - PYFUNCEBLE_DB_PASSWORD="${DB_PASSWORD}"
  - PYFUNCEBLE_DB_PORT="${DB_PORT}"

addons:
  apt:
    packages:
    - tree

install:
  - export PATH="${HOME}/miniconda/bin:${PATH}"
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
    -O miniconda.sh; else wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
    -O miniconda.sh; fi
  - bash miniconda.sh -b -p ${HOME}/miniconda
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda update -q conda
  - conda create -q -n test-environment python="${PYTHON_VERSION}"
  - source activate test-environment
  - python --version --version
  - pip --version
  - conda --version
  - pip install --no-cache-dir -U "git+https://github.com/funilrys/${Pyfunceble_version}"
  #- pip install --no-cache-dir -U pyfunceble-dev dnspython[dnssec,idna]
  - pyfunceble --version
  #- wget -O "${TRAVIS_BUILD_DIR}/setup_travis.sh" "${SCRIPT_SOURCE_URI}/travis/setup_travis.sh"
  #  && sudo chmod +x "${TRAVIS_BUILD_DIR}/setup_travis.sh"
  #- sudo bash "${TRAVIS_BUILD_DIR}/setup_travis.sh"

git:
  depth: 2

script:
  #- truncate -s 0 "${TRAVIS_BUILD_DIR}/run_id"
  #- echo "${TRAVIS_JOB_ID}" > "${TRAVIS_BUILD_DIR}/run_id"
  #- cat "${TRAVIS_BUILD_DIR}/run_id"
  #- bash "${TRAVIS_BUILD_DIR}/dns-test.sh"
  #- pyfunceble --database-type mariadb --ci --dns 95.216.209.53 --whois-lookup -d mypdns.org mypdns.com --logging-level critical
  #- pyfunceble --ci --syntax -ex -w 3 -f https://raw.githubusercontent.com/PyFunceble/ci_test/master/test.list --display-status INVALID --logging-level info
  #- pyfunceble --ci --syntax -ex -w 3 -f https://raw.githubusercontent.com/PyFunceble/ci_test/master/test.list --display-status INVALID --logging-level debug
  #- pyfunceble --ci --syntax -ex -w 3 -f https://raw.githubusercontent.com/PyFunceble/ci_test/master/test.list --display-status INVALID --logging-level warning
  #- pyfunceble --ci --syntax -ex -w 3 -f https://raw.githubusercontent.com/PyFunceble/ci_test/master/test.list --display-status INVALID --logging-level error
  #- pyfunceble --ci --syntax -ex -w 3 -f https://raw.githubusercontent.com/PyFunceble/ci_test/master/test.list --display-status INVALID --logging-level critical
  # - tree -a -I '.git*'

jobs:
  include:
    - stage: "CLI (running) Tests"
      language: generic
      os: linux
      dist: focal
      name: "adblock + syntax #156"
      env:
        - PYTHON_VERSION="3.9.1"
      script:
        - pyfunceble --ci -a --syntax -ex -w $(nproc --ignore=2)
          --adblock -f 'https://raw.githubusercontent.com/easylist/easylist/master/easyprivacy/easyprivacy_trackingservers.txt'
          'https://raw.githubusercontent.com/easylist/easylist/master/easylist_cookie/easylist_cookie_general_hide.txt'
          'https://raw.githubusercontent.com/easylist/easylist/master/fanboy-addon/fanboy_annoyance_specific_block.txt'
          --ci-branch "${TRAVIS_BRANCH}" --ci-distribution-branch "${TRAVIS_BRANCH}" -dbr 0
          --dns doh.powerdns.org --dns-protocol HTTPS
          --dots --share-logs
        - tree --prune -f "${TRAVIS_BUILD_DIR}/.pyfunceble/"
    - language: generic
      os: linux
      dist: focal
      name: "adblock + syntax #156"
      env:
        - PYTHON_VERSION="3.9.1"
      script:
        - pyfunceble --ci -a --database-type mariadb -ex -w $(nproc --ignore=2)
          --adblock -f 'https://raw.githubusercontent.com/easylist/easylist/master/easyprivacy/easyprivacy_trackingservers.txt'
          'https://raw.githubusercontent.com/easylist/easylist/master/easylist_cookie/easylist_cookie_general_hide.txt'
          'https://raw.githubusercontent.com/easylist/easylist/master/fanboy-addon/fanboy_annoyance_specific_block.txt'
          --ci-branch "${TRAVIS_BRANCH}" --ci-distribution-branch "${TRAVIS_BRANCH}" -dbr 0
          --dns doh.powerdns.org --dns-protocol HTTPS
          --dots --share-logs
        - tree --prune -f "${TRAVIS_BUILD_DIR}/.pyfunceble/"

